<div id="tagLegend">
    <?php foreach(Application_Model_Query_Tag::getInstance()->fetchAll() as $tag) { ?>
        <span class="tag"><?php echo $tag->name; ?> = <?php echo $tag->symbol; ?></span>,
    <?php } ?>
</div>

<div id="indexIndex">

    <?php foreach($this->products as $product) { ?>
        <div class="product" 
            style="background-image: url(<?php echo Zend_Registry::get('config')->hosts->images . '/medium/' . $product->getPrimaryProductImage()->id . '.jpg'; ?>);
                    background-repeat: no-repeat;
                    background-position: 0px 40px;"> 
            <div class="name"><a href="/product/view/<?php echo $product->id; ?>"><?php echo $product->name; ?></a></div>
            <div class="farm">from <a href="/farm/view/<?php echo $product->getFarm()->id; ?>"><?php echo $product->getFarm()->name; ?></a></div>
            <div class="tags">
                <?php foreach($product->getProductTags() as $productTag) { ?>
                <span class="tag"><?php echo $productTag->getTag()->symbol; ?></span>
                <?php } ?>
            </div> 
            <div class="left">
                <p class="text"><?php printf("$%.2f", $product->price); ?></p>
            </div>
            <div class="center">
                <p class="text"><?php echo $product->amount; ?></p>
            </div>
            <div class="right">
                <p class="text"><a href="/buyer/addtocart"><img src="/img/addtocart.png" width="24" height="24" /></a>
            </div>
        </div>
    <?php } ?>

</div>
