<div id="indexIndex" class="browser">
        <?php foreach($this->categories as $category) { ?>
            <div class="product" 
                <?PHP if($category->getPrimaryImage()) { ?>
                style="background-image: url(<?php echo Zend_Registry::get('config')->hosts->images . '/medium/' . $category->getPrimaryImage()->id . '.jpg'; ?>);
                        background-repeat: no-repeat;
                        background-position: 0px 40px;"
                <?PHP } ?>> 
                <a href="/product/browse/category/<?PHP echo $category->id; ?>" class="boxlink"></a>
                <div class="name"><a href="/product/browse/category/<?php echo $category->id; ?>"><?php echo $category->name; ?></a></div>
                <div class="farm"></div>
                <div class="tags">
                </div> 
                <div class="left">
                    <p class="text"></p>
                </div>
                <div class="center">
                    <p class="text"><?php echo count($category->getProducts()); ?> products</p>
                </div>
                <div class="right">
                    <p class="text"></a>
                </div>
            </div>
        <?php } ?>
    <div class="clear"></div>
    <?PHP 
        echo $this->paginationControl($this->categories,
                                'Sliding',
                                'pagination_controls.phtml');
    ?>

</div>
