<div class="product"
        <?php if($this->product->getPrimaryProductImage() !== false) { ?> 
        style="background-image: url(<?php echo Zend_Registry::get('config')->hosts->images . '/medium/' . $this->product->getPrimaryProductImage()->id . '.jpg'; ?>);
            background-repeat: no-repeat;
            background-position: 0px 40px;" 
        <?php } ?>>
    <a href="/product/view/id/<?PHP echo $this->product->id; ?>" class="boxlink"></a>
    <div class="name"><a href="/product/view/id/<?php echo $this->product->id; ?>"><?php echo $this->product->name; ?></a></div>
    <div class="farm">from <a href="/farm/view/id/<?php echo $this->product->getFarm()->id; ?>"><?php echo $this->product->getFarm()->name; ?></a></div>
    <div class="tags">
        <?php foreach($this->product->getProductTags() as $this->productTag) { ?>
        <span class="tag"><?php echo $this->productTag->getTag()->symbol; ?></span>
        <?php } ?>
    </div> 
    <div class="left">
        <p class="text"><?php printf("$%.2f/%s", $this->product->price, $this->product->getUnit()->abbreviation); ?></p>
    </div>
    <div class="center">
        <p class="text"><?php echo $this->product->getAmountCurrentlyAvailable() . ' ' . ($this->product->getUnit()->abbreviation == 'ea' ? '' : $this->product->getUnit()->abbreviation); ?></p>
    </div>
    <div class="right">
        <p class="text"><a href="/cart/add/id/<?php echo $this->product->id; ?>"><img src="/img/addtocart.png" width="24" height="24" /></a>
    </div>
</div>

