<div id="tagLegend">
    <?php foreach(Application_Model_Query_Tag::getInstance()->fetchAll() as $tag) { ?>
        <span class="tag"><?php echo $tag->name; ?> = <?php echo $tag->symbol; ?></span>,
    <?php } ?>
</div>


<div id="productBrowse" class="inner">
    <div class="browser">
        <?php 
            foreach($this->paginator as $product) {
                echo $this->partial('product_partial.phtml', array('product'=>$product));
            }
        ?>
        <div class="clear"></div>
        <?PHP 
            echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_controls.phtml');
        ?>
    </div>
</div>
