<div id="tagLegend">
    <?php foreach(Application_Model_Query_Tag::getInstance()->fetchAll() as $tag) { ?>
        <span class="tag"><?php echo $tag->name; ?> = <?php echo $tag->symbol; ?></span>,
    <?php } ?>
</div>


<div id="productBrowse">
    <div class="browser">
        <?php 
            foreach($this->products as $product) {
                echo $this->partial('product_partial.phtml', array('product'=>$product));
            }
        ?>
        <div class="clear"></div>
    </div>
</div>
