<div id="productView">
    <div class="controls">
        <a href="/cart/add/id/<?php echo $this->product->id; ?>">Add to your Cart</a>
    </div>
    <div id="product">
        <div class="tags">
            <?php foreach($this->product->getProductTags() as $productTag) { ?>
                <div class="tag"><?php echo $productTag->getTag()->symbol; ?></div>
            <?php } ?>
        </div> 
        <div class="price">$<?php echo sprintf('%.2f', $this->product->price); ?></div>
        <div class="amount"><?php echo $this->product->amount; ?></div>
        <div class="category"><?php echo $this->product->getCategory()->name; ?></div>
        <div class="name"><?php echo $this->product->name; ?></div>
        <div class="description"><?php echo $this->product->description; ?></div> 
        <div class="images"> 
           <?php foreach($this->product->getProductImages() as $productImage) { ?>
                <div class="image">
                    <img src="<?php echo Zend_Registry::get('config')->hosts->images; ?>/medium/<?php echo $productImage->getImage()->id; ?>.jpg" />
                </div>
            <?php } ?>
        </div>
        <div class="farm">
            <div class="name">
                <a href="/farm/view/id/<?php echo $this->product->getFarm()->id; ?>"><?php echo $this->product->getFarm()->name; ?></a>
            </div>
            <div class="description"><?php echo $this->product->getFarm()->description ?></div>
        </div>
    </div>

</div>
