<div id="customerRegister" class="inner formWrapper">

    <div id="errors">
        <?PHP if(!empty($this->errors)) { ?>
            <?PHP foreach($this->errors as $error) { ?>
                <p><?PHP echo $error; ?></p>
            <?PHP } ?>
        <?PHP } ?>
    </div>
    <form method="POST" action="<?php echo $this->url(); ?>">
        <label for="email">Email</label><input type="text" name="email" /><br />
        <label for="password">Password</label><input type="password" name="password" /><br />
        <label for="confirm">Confirm Password</label><input type="password" name="confirm" /><br />
        <input type="submit" value="Register" /><br />
    </form>
</div>
