<div id="customerRegister">
    <form method="POST" action="/customer/register">
        <label for="email">Email</label><input type="text" name="email" /><br />
        <label for="password">Password</label><input type="password" name="password" /><br />
        <label for="confirm">Confirm Password</label><input type="password" name="confirm" /><br />
        <input type="submit" value="Register" /><br />
    </form>
</div>
