<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
    <title>Open Source Online Farm Market</title>	
    <link rel="stylesheet" type="text/css" href="/style/stylesheet.css" />
    <link rel="stylesheet" type="text/css" href="/style/jquery.Jcrop.css" />   
 
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery.Jcrop.js"></script>
    <script tytpe="text/javascript" src="/js/main.js"></script>
    <?php if(isset($this->js)) { ?>
         <?php foreach($this->js as $script) { ?>
                <script type="text/javascript" src="/js/<?php echo $script; ?>.js"></script>
        <?php } ?>
    <?php } ?>
</head>
<body>
<div id="header">
	<div id="userControls">
        <?php
            $session = new Zend_Session_Namespace('cart');
        ?>
        <?php if(!Zend_Auth::getInstance()->hasIdentity()) { ?>
            <a href="/user/login">Sign in</a> |
            <a href="/customer/register">Customer Signup</a> | 
        <?php } else { ?>
            <a href="/customer/dashboard">Customer Dashboard</a> |
        <?php } ?>
        <a href="/cart/view">View Cart</a> 
            <?php
                if($session->order) { 
                    $totalItems = 0;
                    foreach($session->order->getOrderProducts() as $orderProduct) {
                        $totalItems += $orderProduct->amount;
                    }
                    echo '(' 
                        . count($session->order->getOrderProducts()) . ' products, ' 
                        . $totalItems . ' items, '
                        . sprintf('$%.2f', $session->order->getTotal()) 
                        . ')'; 
                }
            ?>  
    </div>

    <div id="title">Open Source Farm Market</div>

    <div id="information">
        <?php if(Zend_Auth::getInstance()->hasIdentity() && Zend_Auth::getInstance()->getIdentity()->isGrower == true) { ?>
            <a href="/grower/dashboard">Grower Dashboard</a> |
            <a href="/user/logout">Logout</a> | 
        <?php } else if(Zend_Auth::getInstance()->hasIdentity()) { ?>
            <a href="/user/logout">Logout</a> |
        <?php } else if(!Zend_Auth::getInstance()->hasIdentity()) { ?> 
            <a href="/grower/register">Growers Signup</a> |
        <?php } ?>
        <a href="/about">About</a> 
    </div>

    <div id="navigation"> 
        <div id="js-fail"> 
            <a href="/">Home</a> | 
            <a href="/product/browse">Browse Products</a> |
            <a href="/farm/browse">Browse Farms</a>
        </div>
        <!-- This will default to hidden and only be shown if the user has javascript enabled. -->
        <div id="openmenu"><a href="" id="browse-button" >Browse By <img src="/img/arrow_down.png" /></a></div>
        <div id="closemenu"><a href="" id="browse-button" >Browse By <img src="/img/arrow_up_white.png" /></a></div>
        <div id="menu">
            <div id="menu-top">
                <a href="/">Browse Categories</a><br />
                <a href="/product/browse">Browse Products</a><br />
                <a href="/farm/browse">Browse Farms</a><br />
            </div>
            <div id="menu-categories">
                <?PHP foreach(Application_Model_Query_Category::getInstance()->fetchAll() as $category) { ?>
                    <a href="/product/browse/category/<?PHP echo $category->id; ?>"><?PHP echo $category->name; ?></a><br />
                <?PHP } ?>
            </div>
        </div>
    </div>
    
    <div id="search">
        <form method="GET" action="/search/">
        <select name="cat">
        <option value="all">All</option> 
            <?php foreach(Application_Model_Query_Category::getInstance()->fetchAll() as $category) { ?>
                <option value="<?php echo $category->id; ?>"><?php echo $category->name; ?></option>
            <?php } ?>
        </select>
        <input type="text" name="q" /> 
        <input type="submit" value="Search" />
        </form>
    </div>	
</div>
<div id="main">
    <?php echo $this->layout()->content; ?>
    <div class="clear"></div>
</div>
<div id="footer" >
</div>
</body>
</html>


