<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
    <title>Open Source Online Farm Market</title>	
    <link rel="stylesheet" type="text/css" href="/style/stylesheet.css" />
</head>
<body>
<div id="header">
	<div id="userControls">
        <?php
            $session = new Zend_Session_Namespace('buyer');
        ?>
        <a href="/cart/view">View Cart</a> <?php echo ($session->order ? '(' . count($session->order->getOrderProducts()) . ')' : ''); ?>  | 
        <a href="/buyer/account">Your Account</a> <?php echo (Zend_Auth::getInstance()->hasIdentity() ? '(' . Zend_Auth::getInstance()->getIdentity()->email . ')' : ''); ?>
    </div>

    <div id="title">Open Source Farm Market</div>

    <div id="information">
        <a href="/about">About</a> |
        <a href="/user/login">Grower Login</a>
    </div>

    <div id="navigation"> 
        <a href="/product/browse">Browse Products</a> |
        <a href="/farm/browse">Browse Farms</a>
    </div>

  
    

    <div id="search">
        <form method="GET" action="/search/">
        <select name="cat">
        <option value="all">All</option> 
        <?php 
            $categories = Application_Model_Query_Category::getInstance()->fetchAll();
            foreach($categories as $category) { ?>
                <option value="<?php echo $category->id; ?>"><?php echo $category->name; ?></option>
            <?php } ?>
        </select>
        <input type="text" name="q" /> 
        <input type="submit" value="Search" />
        </form>
    </div>	
</div>
<div id="main">
    <?php echo $this->layout()->content; ?>
</div>
<div id="footer" >
</div>
</body>
</html>


