
<?PHP echo $this->partial('admin_controls_partial.phtml'); ?>
<div id="adminCategories" class="viewPanel formWrapper">
    <table>
        <tr><td></td><td>Category Name</td><td>Number of Products</td><td><a href="/admin/edit-category">Add Category</a></td></tr>
        <?PHP foreach($this->categories as $category) { ?>
            <tr>
                <td><img src="<?PHP echo ($category->getPrimaryImage() ? $category->getPrimaryImage()->getImageURL('small') : ''); ?>" /></td>
                <td><?PHP echo $category->name; ?></td>
                <td><?PHP echo count($category->getProducts()); ?></td>
                <td>
                    <a href="/admin/edit-category/id/<?php echo $category->id; ?>">Edit</a>
                    <a href="/admin/delete-category/id/<?php echo $category->id; ?>">Delete</a>
                </td>
            </tr> 
        <?PHP } ?>
    </table>
</div>
